flowchart TD
    subgraph Structure
        EventMachine ---> UIElement
    end
    subgraph Component
        UIElement --> Class[Class Component] 
        Class[Class Component] --> template
        template --> render
        UIElement --> Function[Function Component] 
        Function[Function Component] --> function
    end
    subgraph Rendering    
        function --> render
        render --> FirstRender 
        FirstRender -- attach to parent --> onMounted
        render --> Reconcile
        Reconcile -- update dom element --> onUpdated
    end
    subgraph Destruction    
        onMounted   ---> onDestroyed
        onUpdated   ---> onDestroyed
        onDestroyed -- detach from parent --> onUnmounted
        onUnmounted --> ClearHooks
    end

    
