export const pages = [
  "Introduction",
  {
    link: "/pages/introduction/getting-started.html",
    title: "Getting Started",
  },
  {
    link: "/pages/introduction/install.html",
    title: "Install",
  },
  "Sapa Basics",
  {
    link: "/pages/sapa/basic.html",
    title: "Sapa Basic",
  },
  {
    link: "/pages/sapa/feature-jsx.html",
    title: "Jsx",
  },
  {
    link: "/pages/sapa/feature-component.html",
    title: "Component",
  },
  {
    link: "/pages/sapa/feature-hook.html",
    title: "Hook",
  },
  {
    link: "/pages/sapa/feature-dom.html",
    title: "DOM",
  },
  {
    link: "/pages/sapa/feature-store-message.html",
    title: "Store & Message",
  },

  "Sapa Extensions",
  {
    link: "/pages/sapa/feature-handler.html",
    title: "Handler",
  },
  {
    link: "/pages/sapa/feature-custom-hook.html",
    title: "Custom Hook",
  },
  {
    link: "/pages/sapa/feature-router.html",
    title: "Router",
  },
  {
    link: "/pages/sapa/feature-api.html",
    title: "API",
  },
  "Design System",
  { link: "/pages/design-system/color.html", title: "Color" },
  { link: "/pages/design-system/typography.html", title: "Typography" },
  { link: "/pages/design-system/spacing.html", title: "Spacing" },
  { link: "/pages/design-system/grid.html", title: "Grid" },
  "UI Component",

  { link: "/pages/ui-component/router.html", title: "1. Router" },
  { link: "/pages/ui-component/icons.html", title: "4. Icons" },
  { link: "/pages/ui-component/button.html", title: "5. Button" },
  { link: "/pages/ui-component/button-group.html", title: "5-1. ButtonGroup" },
  { link: "/pages/ui-component/icon-button.html", title: "6. Icon Button" },
  { link: "/pages/ui-component/radio.html", title: "7. Radio" },
  { link: "/pages/ui-component/checkbox.html", title: "8. Checkbox" },
  { link: "/pages/ui-component/menu.html", title: "9. Menu" },
  { link: "/pages/ui-component/context-menu.html", title: "10. Context Menu" },
  { link: "/pages/ui-component/option-menu.html", title: "11. Option Menu" },
  { link: "/pages/ui-component/dialog.html", title: "12. Dialog" },
  { link: "/pages/ui-component/toolbar.html", title: "13. Toolbar" },
  { link: "/pages/ui-component/tools.html", title: "14. Tools" },
  { link: "/pages/ui-component/alert.html", title: "5. Alert" },
  { link: "/pages/ui-component/notification.html", title: "15. Notification" },
  { link: "/pages/ui-component/visual-bell.html", title: "16. Visual Bell" },
  {
    link: "/pages/ui-component/visual-bell-target.html",
    title: "16-1. Visual Bell with Target",
  },
  { link: "/pages/ui-component/tooltip.html", title: "17. Tooltip" },
  { link: "/pages/ui-component/panel.html", title: "18. Panel" },
  { link: "/pages/ui-component/input-editor.html", title: "19. Input Editor" },
  { link: "/pages/ui-component/input-paint.html", title: "20. Input Paint" },
  { link: "/pages/ui-component/color-mixer.html", title: "21. Color Mixer" },
  { link: "/pages/ui-component/color-grid.html", title: "22. Color Grid" },
  {
    link: "/pages/ui-component/virtual-scroll.html",
    title: "23. Virtual Scroll",
  },
  { link: "/pages/ui-component/flex.html", title: "24. Flex Layout" },
  { link: "/pages/ui-component/grid.html", title: "25. Grid Layout" },
  { link: "/pages/ui-component/option-strip.html", title: "26. Option Strip" },
  {
    link: "/pages/ui-component/view.html",
    title: "27. View(pure element tag)",
  },
  { link: "/pages/ui-component/tabs.html", title: "28. Tabs" },
  { link: "/pages/ui-component/data-editor.html", title: "29. Data Editor" },
  { link: "/pages/ui-component/global-state.html", title: "30. Global State" },
  { link: "/pages/ui-component/panzoom.html", title: "31. PanZoom" },
  { link: "/pages/ui-component/event-panel.html", title: "32. EventPanel" },
  { link: "/pages/ui-component/to-html.html", title: "33. To Html " },
  {
    link: "/pages/ui-component/app-layout.html",
    title: "34. Layout - AppLayout ",
  },
];
